---

domain: "192.168.56.4.nip.io"
host_id: vagrant-local
rails_env: staging

admin_email: admin@192.168.56.4.nip.io

mail_domain: 192.168.56.4.nip.io

certbot_domains:
  - 192.168.56.4.nip.io
  - 192.168.56.4

postgres_listen_addresses:
  - localhost
  - 192.168.56.4

custom_hba_entries:
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"

multiredis_use_ppa: false
